spring:
  datasource:
    name: root
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/boki?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    #连接池配置
    type: org.apache.commons.dbcp2.BasicDataSource  #开启dbcp2连接池
    dbcp2:
      validation-query: SELECT 1   #默认测试连接语句
      connection-init-sqls: SET NAMES utf8mb4    
       
mybatis:
  mapper-locations: classpath:com.yzsm.boki.mapper/*.xml
  
server:
  servlet:
    context-path: /boki
  port: 8080
  max-http-header-size:    10240
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto    uri-encoding: UTF-8